UserStoryManager/Models/UserStory.cs
using System;
namespace UserStoryManager.Models
{
    public class UserStory : BacklogItem
    {
        public string Story { get; set; }
        public string AcceptanceCriteria { get; set; }
        public int BusinessValue { get; set; }
        public string StoryPoints { get; set; }

        public UserStory()
        {
            
        }

        public UserStory(string title, string description, int state, int priority, TeamMember developer, TeamMember creator, DateTime dateCreated, Sprint sprint, string note, int estimatedHours, int usedHours, DateTime dateTimeStarted, string story, string acceptanceCriteria, int businessValue, string storyPoints) : base(title, description, state, priority, developer, creator, dateCreated, sprint, note, estimatedHours, usedHours, dateTimeStarted)
        {
            Story = story;
            AcceptanceCriteria = acceptanceCriteria;
            BusinessValue = businessValue;
            StoryPoints = storyPoints;
        }

        public override string GetId()
        {
            return "U" + Id;
        }
    }
}

UserStoryManager/Pages/DeleteUserStory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages
{
    public class DeleteUserStoryModel : PageModel
    {
        [BindProperty] public UserStory UserStory { get; set; }
        private UserStoryService userStoryService;

        public DeleteUserStoryModel(UserStoryService userStoryService)
        {
            this.userStoryService = userStoryService;
        }
        public void OnGet(int id)
        {
            UserStory = userStoryService.GetUserStory(id);
        }

        public IActionResult OnPost()
        {
            UserStory deletedUserStory = userStoryService.DeleteUserStory(UserStory.Id);
            return RedirectToPage("UserStories");
        }
    }
}

UserStoryManager/Pages/UserStories.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages
{
    public class UserStoriesModel : PageModel
    {
        private UserStoryService userStoryService;
        public List<UserStory> UserStories { get; private set; }

        public UserStoriesModel(UserStoryService userStoryService)
        {
            this.userStoryService = userStoryService;
        }
        public void OnGet()
        {
            UserStories = userStoryService.GetUserStories();
        }
    }
}

UserStoryManager/Pages/UserStory/BacklogUserStories.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages.UserStory
{
    public class BacklogUserStoriesModel : PageModel
    {
        private StoryBoardService storyBoardService;
        public StoryBoard StoryBoard { get; set; }

        public BacklogUserStoriesModel(StoryBoardService storyBoardService)
        {
            this.storyBoardService = storyBoardService;
        }

        public void OnGet()
        {
            StoryBoard = storyBoardService.GetStoryBoard();
        }

        public IActionResult OnPost(int id)
        {
            storyBoardService.ChangeState(id);
            return RedirectToPage("/UserStory/BacklogUserStories");
        }
    }

}

UserStoryManager/Pages/UserStory/CreateUserStory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages.UserStory
{
    public class CreateUserStoryModel : PageModel
    {
        private StoryBoardService _storyBoardService;
        [BindProperty] public Models.UserStory UserStory { get; set; }
        public StoryBoard StoryBoard { get; set; }

        public CreateUserStoryModel(StoryBoardService storyBoardService)
        {
            _storyBoardService = storyBoardService;
        }
        public void OnGet()
        {
            StoryBoard = _storyBoardService.GetStoryBoard();
        }
    }
}

UserStoryManager/Pages/UserStory/DeleteUserStory.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Services;

namespace UserStoryManager.Pages.UserStory
{
    public class DeleteUserStoryModel : PageModel
    {
        [BindProperty] public Models.Card Card { get; set; }
        private StoryBoardService storyBoardService;
        

        public DeleteUserStoryModel(StoryBoardService userStoryService)
        {
            this.storyBoardService = userStoryService;
        }
        public void OnGet(int id)
        {
            Card = storyBoardService.GetUserStory(id);
        }

        public IActionResult OnPost()
        {
            Models.Card deletedUserStory = storyBoardService.DeleteUserStory(Card.Id);
            return RedirectToPage("/UserStory/UserStories");
        }
    }
}

UserStoryManager/Pages/UserStory/UserStories.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages.UserStory
{
    public class UserStoriesModel : PageModel
    {
        private StoryBoardService _storyBoardService;
        public StoryBoard StoryBoard { get; set; }
        

        public UserStoriesModel(StoryBoardService storyBoardService)
        {
            this._storyBoardService = storyBoardService;
        }

        public void OnGet()
        {
            StoryBoard = _storyBoardService.GetStoryBoard();
        }

        public IActionResult OnPost(int id)
        {
            StoryBoard = _storyBoardService.GetStoryBoard();
            _storyBoardService.ChangeState(id);
            return Page();
        }

        public IActionResult OnPostReset(int id)
        {
            StoryBoard = _storyBoardService.GetStoryBoard();
            _storyBoardService.ResetState(id);
            return Page();
        }
    }
    
}

UserStoryManager/Pages/UserStory/UserStoryDetail.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages.UserStory
{
    public class UserStoryDetailModel : PageModel
    {
        [BindProperty] public Models.Card CardStory { get; set; }
        public StoryBoard StoryBoard { get; set; }
        private StoryBoardService _storyBoardService;

        public UserStoryDetailModel(StoryBoardService storyBoardService)
        {
            this._storyBoardService = storyBoardService;
        }
        public void OnGet(int id)
        {
            StoryBoard = _storyBoardService.GetStoryBoard();
            CardStory = _storyBoardService.GetUserStory(id);
        }
    }
}

UserStoryManager/Pages/UserStoryDetail.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStoryManager.Models;
using UserStoryManager.Services;

namespace UserStoryManager.Pages
{
    public class UserStoryDetailModel : PageModel
    {
        [BindProperty] public UserStory UserStory { get; set; }
        public List<UserStory> UserStories { get; private set; }
        private UserStoryService userStoryService;

        public UserStoryDetailModel(UserStoryService userStoryService)
        {
            this.userStoryService = userStoryService;
        }
        public void OnGet(int id)
        {
            UserStories = userStoryService.GetUserStories();
            UserStory = userStoryService.GetUserStory(id);
        }
    }
}

UserStoryManager/Pages/UserStory/BacklogUserStories.cshtml
@page
@using UserStoryManager.Models
@model UserStoryManager.Pages.UserStory.BacklogUserStoriesModel
@{
}
<a asp-page="CreateUserStory">Create New</a>
<div class="card">
    <div class="card-header">Backlog</div>
    <div class="card-body">
        @foreach (var us in Model.StoryBoard.Cards)
        {
            if (us.State == 0)
            {
                <div class="card mb-2" style="width: 100%;">
                <div class="card-header p-2">
                    <h5 class="card-title">(@us.Id) @us.Title</h5>
                </div>
                <div class="card-body">@us.Description</div>
                    <div class="card-footer">
                        <a class="btn" type="button" style="float: left" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                        <a class="btn" type="button" style="float: left" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                        <form method="post">
                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                        </form>
                    </div>
                </div>
            }
        }
    </div>
</div>

UserStoryManager/Pages/UserStory/CreateUserStory.cshtml
@page
@model UserStoryManager.Pages.UserStory.CreateUserStoryModel
@{
}
<div class="card">
    <div class="card-header">Backlog</div>
    <div class="card-body">
        @foreach (var us in Model.StoryBoard.Cards)
        {
            if (us.State == 0)
            {
                <div class="card mb-2" style="width: 100%;">
                    <div class="card-header p-2">
                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                    </div>
                    <div class="card-body">@us.Description</div>
                    <div class="card-footer">
                        <a class="btn" type="button" style="float: left" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                        <a class="btn" type="button" style="float: left" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                        <form method="post">
                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                        </form>
                    </div>
                </div>
            }
        }
    </div>
</div>

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title"><b>Create new User Story </b></div>
                <a type="button" class="close" asp-page="ProductBacklog">&times;</a>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.Title" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.Title" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.Description" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.Description" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.Story" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.Story" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.AcceptanceCriteria" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.AcceptanceCriteria" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.BusinessValue" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.BusinessValue" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.Priority" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.Priority" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.UserStory.StoryPoints" class="control-lable"></label>
                        <input asp-for="@Model.UserStory.StoryPoints" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function() {
            $("#myModal").modal({ backdrop: "static" });
            $("#myModal").modal('show');
        })
    </script>
}

UserStoryManager/Pages/UserStory/DeleteUserStory.cshtml
@page "{id:int}"
@using UserStoryManager.Models
@model UserStoryManager.Pages.UserStory.DeleteUserStoryModel
@{
}
<h1>Delete Confirmation</h1>
<header>DeleteUserStory</header>
<div class="alert alert-danger">
    <h5>Are you sure you want to delete the User Story - @Model.Card.Title</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href='javascript:history.go(-1)' class="btn btn-primary">No</a>
    </form>
</div>

UserStoryManager/Pages/UserStory/UserStories.cshtml
@page
@using UserStoryManager.Models
@using System.Reflection.Metadata.Ecma335
@model UserStoryManager.Pages.UserStory.UserStoriesModel
@{
}
<h1>User Stories</h1>

@*  0 = Stories
    1 =  To Do
    2 = In Progress
    3 = To Verify
    4 = Donedone*@


<div class="container container-fixer">
    <div class="row flex-row flex-sm-nowrap pt-3">
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">To Do</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 1)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post" asp-page="UserStoriesModel">
                                        
                                        

                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Doing</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 2)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post" asp-page="UserStoriesModel">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Done</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 3)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <button onclick="DeleteConfirmation()">Button</button>
                                        <form method="post" asp-page="UserStoriesModel">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Done Done</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 4)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-page-handler="Reset" asp-route-id="@us.Id"><i class="fa-solid fa-backward-fast"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*<button onclick="DeleteConfirmation()">Button</button>
@section Scripts{
    <script>
        function DeleteConfirmation() {
            var result = confirm("You sure my negro?");
        }
    </script>
}*@

UserStoryManager/Pages/UserStory/UserStoryDetail.cshtml
@page
@model UserStoryManager.Pages.UserStory.UserStoryDetailModel
@{
}
<h1>User Stories</h1>

@*  0 = Stories
    1 =  To Do
    2 = In Progress
    3 = To Verify
    4 = Donedone*@


<div class="container container-fixer">
    <div class="row flex-row flex-sm-nowrap pt-3">
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">To Do</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 1)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post" asp-page="UserStoriesModel">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Doing</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 2)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post" asp-page="UserStoriesModel">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Done</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 3)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post" asp-page="UserStoriesModel">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <button class="btn" type="submit" style="float: right" asp-route-id="@us.Id"><i class="fa fa-arrow-right"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-light">
                <div class="card-body">
                    <h6 class="card-title text-uppercase text-truncate py-2">Done Done</h6>
                    <div class="items border border-light">
                        @foreach (var us in Model.StoryBoard.Cards)
                        {
                            if (us.State == 4)
                            {
                                <div class="card mb-2" style="width: 100%;">
                                    <div class="card-header p-2">
                                        <h5 class="card-title">(@us.Id) @us.Title</h5>
                                    </div>
                                    <div class="card-body">
                                        @us.Description
                                    </div>
                                    <div class="card-footer">
                                        <form method="post">
                                            <a class="btn" type="button" asp-page="DeleteUserStory" asp-route-id="@us.Id"><i class="fa fa-trash"></i></a>
                                            <a class="btn" type="button" asp-page="UserStoryDetail" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></a>
                                            <a class="btn" type="button" title="submit" asp-route-id="@us.Id"><i class="fa-solid fa-angles-left"></i></a>
                                            <button class="btn" type="submit" style="float:right" asp-page-handler="Reset" asp-route-id="@us.Id"><i class="fa fa-info-circle"></i></button>
                                        </form>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><small class="text-muted">(@Model.CardStory.Id)</small>@Model.CardStory.Title</h5>
                <a type="button" class="close" asp-page="UserStories">&times;</a>
            </div>
            <div class="modal-body">
                @if (Model.CardStory is Models.UserStory)
                {
                    var us = (Models.UserStory) Model.CardStory;
                    <p><b>Description</b>@us.Description</p>
                    <p><b>Business Value</b>@us.BusinessValue</p>
                    <p><b>Creation Date</b>@us.DateCreated</p>
                    <p><b>Priority</b>@us.Priority</p>
                    <p><b>Story Points</b>@us.StoryPoints</p>
                }
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-danger" asp-page="UserStories">Close</a>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#myModal").modal({ backdrop: "static" });
            $("#myModal").modal("show");
        });
    </script>
}